apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisbgp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisbgp
  template:
    metadata:
      labels:
        app: redisbgp
    spec:
      containers:
      - name: redisbgp
        image: localhost:5000/redisforkuber2
        ports:
        - containerPort: 6381
        - containerPort: 6382
        - containerPort: 6383
        - containerPort: 6384
        - containerPort: 6385
        - containerPort: 6386
        - containerPort: 6387
        - containerPort: 6388

---

apiVersion: v1
kind: Service
metadata:
  name: redisbgp
spec:
  selector:
    app: redisbgp
  ports:
    - name: port1
      protocol: TCP
      port: 6381
      targetPort: 6381
    - name: port2
      protocol: TCP
      port: 6382
      targetPort: 6382
    - name: port3
      protocol: TCP
      port: 6383
      targetPort: 6383
    - name: port4
      protocol: TCP
      port: 6384
      targetPort: 6384
    - name: port5
      protocol: TCP
      port: 6385
      targetPort: 6385
    - name: port6
      protocol: TCP
      port: 6386
      targetPort: 6386
    - name: port7
      protocol: TCP
      port: 6387
      targetPort: 6387
    - name: port8
      protocol: TCP
      port: 6388
      targetPort: 6388